# Generated by Django 5.2.15 on 2026-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciergerequest',
            name='request_type',
            field=models.CharField(choices=[('experience_biolens', 'Experience BioLens'), ('workspace_request', 'Workspace request')], max_length=40),
        ),
    ]
