# Generated by Django 5.2.15 on 2026-09-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0002_alter_conciergerequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciergerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
